name: Run Python Script on Schedule or Manually

on:
  # Schedule trigger: Run the script daily at 12:00 AM UTC
  schedule:
    - cron: "0 0 * * *"

  # Manual trigger
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Check out repository
      uses: actions/checkout@v3

    
    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9" # Specify the Python version

    # Step 3: Install dependencies (if needed)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run your Python script
   
    
    - name: Run script with environment variables
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      run: python upload.py
